[project]
name = "senior-data-engineer-technical-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-postgres>=1.9.0",
    "polars>=1.26.0",
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
