analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      port: ${POSTGRES_PORT}
      dbname: analytics
      schema: core